---
# Elbrus specific package installations
- include_tasks: Elbrus.yml
  when: ansible_os_family  == "Elbrus"

# RedHat specific package installations
- include_tasks: RedHat.yml
  when: ansible_os_family  == "RedHat"

# Debian specific package installations
- include_tasks: Debian.yml
  when: ansible_os_family  == "Debian"
