---
- name: install required system packages
  apt: name={{ item }} state=latest
  with_items:
      - runit
      - sudo

- name: create users
  user: name={{ runit_service_user }} comment="runit {{ runit_service_name }}"

- name: create runit services dirs
  file: path=/etc/sv/{{ runit_service_name }}/log state=directory

- name: put runit services files
  template: src=etc/sv/service/{{ item }} dest=/etc/sv/{{ runit_service_name }}/{{ item }} owner=root group=root mode=0755
  with_items:
    - log/run
    - run
  notify: runit restart

- name: enable runit services
  file: src=../sv/{{ runit_service_name }} dest=/etc/service/{{ runit_service_name }} state=link
  notify: runit restart
