---

- name: purge upstart in ubuntu if it uses systemd
  apt: name=upstart state=absent purge=yes
  when: ansible_service_mgr == "systemd" and ansible_distribution == "Ubuntu"

- name: install required system packages
  apt: name={{ item }} state=present
  with_items:
      - runit
      - sudo
  when: ansible_os_family == "Debian"

- include_tasks: Elbrus.yml
  when: ansible_os_family == "Elbrus"

- name: create users
  user: name={{ runit_service_user }} comment="runit service user"
  when: runit_service_user != 'root'

- name: create runit services dirs
  file: path=/etc/sv/{{ runit_service_name }}/log state=directory

- name: put runit services files
  template: src={{ item }} dest=/etc/sv/{{ runit_service_name }}/{{ item }} owner=root group=root mode=0755
  with_items:
    - run
  notify: runit restart {{ runit_service_name }}
  when: ansible_os_family == "Debian"

- name: put runit services files
  template: src={{ item }} dest=/etc/sv/{{ runit_service_name }}/{{ item }} owner=root group=root
  with_items:
    - run
  when: ansible_os_family == "Elbrus"

- name: put runit services files
  command: chmod 0755 /etc/sv/{{ runit_service_name }}/{{ item }}
  with_items:
    - run
  when: ansible_os_family == "Elbrus"

- include_tasks: prometheus.yml
  when: runit_prometheus_stats

- name: put runit services log files
  template: src={{ item }} dest=/etc/sv/{{ runit_service_name }}/{{ item }} owner=root group=root mode=0755
  with_items:
    - log/run
  notify: runit restart {{ runit_service_name }}/log
  when: ansible_os_family == "Debian"

- name: put runit services log files
  template: src={{ item }} dest=/etc/sv/{{ runit_service_name }}/{{ item }} owner=root group=root
  with_items:
    - log/run
  notify: runit restart {{ runit_service_name }}/log
  when: ansible_os_family == "Elbrus"

- name: put runit services log files
  command: chmod 0755 /etc/sv/{{ runit_service_name }}/{{ item }}
  with_items:
    - log/run
  notify: runit restart {{ runit_service_name }}/log
  when: ansible_os_family == "Elbrus"

- name: enable runit services
  file: src=../sv/{{ runit_service_name }} dest=/etc/service/{{ runit_service_name }} state=link
  when: ansible_os_family  == "Debian"

- name: enable runit services
  file: src=/etc/sv/{{ runit_service_name }} dest=/service/{{ runit_service_name }} state=link
  when: ansible_os_family  == "Elbrus"

- name: wait for runit to handle service
  wait_for: path=/etc/sv/{{ runit_service_name }}/supervise/status
  when: runit_allow_user_control

- name: put runit services log config files
  template: src=log/{{ item }} dest=/var/log/{{ runit_service_name }}/{{ item }} owner=root group=root mode=0755
  with_items:
    - config
  notify: runit hup {{ runit_service_name }}/log
  when: ansible_os_family  == "Debian"

- name: put runit services log config files
  template: src=log/{{ item }} dest=/var/log/{{ runit_service_name }}/{{ item }} owner=root group=root
  with_items:
    - config
  notify: runit hup {{ runit_service_name }}/log
  when: ansible_os_family  == "Elbrus"

- name: put runit services log config files
  command: chmod 0755 /var/log/{{ runit_service_name }}/{{ item }}
  with_items:
    - config
  notify: runit hup {{ runit_service_name }}/log
  when: ansible_os_family  == "Elbrus"

- name: create control directory
  file: dest=/etc/sv/{{ runit_service_name }}/control state=directory

- name: put runit control/t file
  template: src={{ item }} dest=/etc/sv/{{ runit_service_name }}/{{ item }} owner=root group=root mode=0755
  with_items:
    - control/t
  when: ansible_os_family  == "Debian"

- name: put runit control/t file
  template: src={{ item }} dest=/etc/sv/{{ runit_service_name }}/{{ item }} owner=root group=root
  with_items:
    - control/t
  when: ansible_os_family  == "Elbrus"

- name: put runit control/t file
  command: chmod 0755 /etc/sv/{{ runit_service_name }}/{{ item }}
  with_items:
    - control/t
  when: ansible_os_family  == "Elbrus"

- name: allow {{ runit_service_user }} to controll the {{ runit_service_name }} service
  file: dest=/etc/sv/{{ runit_service_name }}/{{ item.d }} mode={{ item.m }} owner={{ item.o }}
  with_items:
      - { d: supervise,         m: 755, o: root }
      - { d: supervise/ok,      m: 600, o: "{{ runit_service_user }}"}
      - { d: supervise/control, m: 600, o: "{{ runit_service_user }}"}
      - { d: supervise/status,  m: 644, o: "{{ runit_service_user }}"}
  when:
    - runit_allow_user_control
    - ansible_os_family  == "Debian"
