#!/bin/bash -eu

LOG_FOLDER=/var/log/{{ runit_service_name }}

mkdir -p "$LOG_FOLDER"
exec svlogd -tt -b {{ runit_log_buflen }} -l {{ runit_log_linelen if runit_log_linelen < runit_log_buflen else runit_log_buflen - 1 }} "$LOG_FOLDER"
