#!/bin/bash -eu
exec 2>&1

ulimit -n {{ runit_service_file_limit }}

{% if runit_service_env|length > 0 %}
export {% for k,v in runit_service_env.iteritems() %}{{ k }}="{{ v }}" {% endfor %}
{% endif %}

{% if runit_service_user == 'root' %}
exec {{ runit_service_command }} {{ runit_service_params }}
{% else %}
exec chpst -u {{ runit_service_user }} "{{ runit_service_command }}" {{ runit_service_params }}
{% endif %}
